language: python

sudo: false

python:
  - 3.4
  - 3.3

install:
  - pip install werkzeug coverage coveralls pytest

script:
  - coverage run --source=anillo -m py.test -v --tb=native

after_success:
  - coveralls
